### ISSUE TITLE
Conteúdo da página "Sobre a PHP PR"

### ISSUE THREAD

**Issue by nandomoreirame** [phppr/docker-phppr.org#10]

**Comment by nandomoreirame** [comment]
Pessoal, o que vocês acham?

> O grupo Grupo de Desenvolvedores do estado do Paraná foi idealizado após o evento do PHPConference Brasil onde o Paraná era um dos únicos que não possuía um grupo do estado, o grupo visa aproximar desenvolvedores de todo o estado do Paraná e NÃO somente de Curitiba.
Começamos com o grupo no Facebook e agora estamos com projetos no Github, perfil no Twitter e também um canal no Slack, entra lá!
Os canais foram criados para a produção de conteúdo, troca de experiências, orientação e até mesmo para tirar dúvidas referente a PHP e outras tecnologias.
Como Contribuir com o PHPPR?
Veja a página “Como Contribuir” para saber mais como contribuir com o grupo.
Seja Bem vindo ao PHPPR.org!

Eu publiquei aqui > http://phppr.org/sobre-a-phppr/

**Comment by jeanmalves** [comment]
Segue minha sugestão.

O grupo de desenvolvedores do estado do Paraná, Brasil foi idealizado após
o evento do PHPConference Brasil. O grupo visa aproximar desenvolvedores de
todo o estado do Paraná.
Começamos com o grupo no Facebook e agora estamos com projetos no Github,
perfil no Twitter e também um canal no Slack, entra lá!
Os canais foram criados para a produção de conteúdo, troca de experiências,
orientação e até mesmo para tirar dúvidas referente a PHP e outras
tecnologias.
Como Contribuir com o PHPPR?
Veja a página “Como Contribuir” para saber mais como contribuir com o grupo.
Seja Bem vindo ao PHPPR.org!

Em 17/02/2017 22:15, "Fernando Moreira" <notifications@github.com> escreveu:

Pessoal, o que vocês acham?

O grupo Grupo de Desenvolvedores do estado do Paraná foi idealizado após o
evento do PHPConference Brasil onde o Paraná era um dos únicos que não
possuía um grupo do estado, o grupo visa aproximar desenvolvedores de todo
o estado do Paraná e NÃO somente de Curitiba.
Começamos com o grupo no Facebook e agora estamos com projetos no Github,
perfil no Twitter e também um canal no Slack, entra lá!
Os canais foram criados para a produção de conteúdo, troca de experiências,
orientação e até mesmo para tirar dúvidas referente a PHP e outras
tecnologias.
Como Contribuir com o PHPPR?
Veja a página “Como Contribuir” para saber mais como contribuir com o grupo.
Seja Bem vindo ao PHPPR.org!

Eu publiquei aqui > http://phppr.org/sobre-a-phppr/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/phppr/phppr.org/issues/10#issuecomment-280801786>, or mute
the thread

**Comment by nandomoreirame** [comment]
não consegui ver o que mudou @jeanmalves

**Comment by nandomoreirame** [comment]
Ah, apenas o **, Brasil** depois do Paraná?

**Comment by jeanmalves** [comment]
Rss removi outras coisas la. Só achei algumas coisas que estavam sobrando. Segue:

O grupo de desenvolvedores do estado do Paraná, Brasil foi idealizado após
o evento do PHPConference Brasil. O grupo visa aproximar desenvolvedores de
todo o estado do Paraná.
Começamos com o grupo no Facebook e agora estamos com projetos no Github,
perfil no Twitter e também um canal no Slack, entra lá!
Os canais foram criados para a produção de conteúdo, troca de experiências,
orientação e até mesmo para tirar dúvidas referente a PHP e outras
tecnologias.
Como Contribuir com o PHPPR?
Veja a página “Como Contribuir” para saber mais como contribuir com o grupo.
Seja Bem vindo ao PHPPR.org!

**Comment by jeanmalves** [comment]
O primeiro parágrafo

**Comment by nandomoreirame** [comment]
Acho que não ha necessidade desse **, Brasil** depois do Paraná, o grupo é para pessoas aqui do Brasil então todos sabem que o Paraná fica no Brasil 😄 

Não entendi ainda o que vc removeu. huahueahehua

**Comment by nandomoreirame** [comment]
vc tirou: **o grupo visa aproximar desenvolvedores de todo o estado do Paraná e NÃO somente de Curitiba.** ??

**Comment by jeanmalves** [comment]
A parte de não somente de cueiriba, acho q não precisa e tbm a parte de não ter o grupo no estado. Só dei uma reajustada no parágrafo.

**Comment by nandomoreirame** [comment]
Talvez assim?

> O grupo Grupo de Desenvolvedores do estado do Paraná foi idealizado após o evento do PHPConference Brasil onde o Paraná era um dos únicos que não possuía um grupo do estado, o grupo visa aproximar desenvolvedores de todo o estado do Paraná.
Começamos com o grupo no Facebook e agora estamos com projetos no Github, perfil no Twitter e também um canal no Slack, entra lá!
Os canais foram criados para a produção de conteúdo, troca de experiências, orientação e até mesmo para tirar dúvidas referente a PHP e outras tecnologias.
Como Contribuir com o PHPPR?
Veja a página “Como Contribuir” para saber mais como contribuir com o grupo.
Seja Bem vindo ao PHPPR.org!

**Comment by jeanmalves** [comment]
Está repetindo ae grupo Grupo, letra maiúscula somente o nome do . Acho desnecessário essa parte "o Paraná era um dos únicos que não possuía um grupo do estado".
É uma sugestão, veja ae o que for melhor.

**Comment by jeanmalves** [comment]
Entendi agora ali a repetição. O nome do grupo coloque entre aspas, melhor pra entender.

**Comment by nandomoreirame** [comment]
Ah é vdd haueheaheu

**Comment by nandomoreirame** [comment]
> O Grupo de Desenvolvedores do estado do Paraná foi idealizado após o evento do PHPConference Brasil, o grupo visa aproximar desenvolvedores de todo o estado do Paraná.
Começamos com o grupo no Facebook e agora estamos com projetos no Github, perfil no Twitter e também um canal no Slack, entra lá!
Os canais foram criados para a produção de conteúdo, troca de experiências, orientação e até mesmo para tirar dúvidas referente a PHP e outras tecnologias.
Como Contribuir com o PHPPR?
Veja a página “Como Contribuir” para saber mais como contribuir com o grupo.
Seja Bem vindo ao PHPPR.org!

**Comment by nandomoreirame** [comment]
Done.
